import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../Component/Navbar";
import Footerpage from "./Footer/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Word Tide",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar></Navbar>
        <main className="min-h-screen">{children}</main>
       <Footerpage></Footerpage>
      </body>
    </html>
  );
}
